# Generated by Django 5.2.4 on 2025-12-17 12:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agreements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(db_index=True, max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('national_id', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('total_purchases', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_purchase_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('first_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(limit_choices_to={'role': 'seller'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-last_purchase_date'],
                'indexes': [models.Index(fields=['phone'], name='sales_custo_phone_43e3c6_idx'), models.Index(fields=['-last_purchase_date'], name='sales_custo_last_pu_5c3c73_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('sales_count', 'Number of Sales'), ('revenue', 'Revenue Target'), ('profit', 'Profit Target')], max_length=15)),
                ('target_value', models.DecimalField(decimal_places=2, help_text='Target value to achieve', max_digits=12)),
                ('achieved_value', models.DecimalField(decimal_places=2, default=0, help_text='Current achieved value', max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_achieved', models.BooleanField(default=False)),
                ('achievement_date', models.DateTimeField(blank=True, null=True)),
                ('incentive_amount', models.DecimalField(decimal_places=2, default=0, help_text='Bonus for achieving target', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(limit_choices_to={'role': 'seller'}, on_delete=django.db.models.deletion.CASCADE, related_name='sales_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Target',
                'verbose_name_plural': 'Sales Targets',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['seller', 'is_active'], name='sales_sales_seller__6fdfe4_idx'), models.Index(fields=['start_date', 'end_date'], name='sales_sales_start_d_3446ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalesTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, help_text='Unique transaction identifier', max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('sale_price', models.DecimalField(decimal_places=2, help_text='Final sale price', max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Purchase/cost price', max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0, help_text='Profit = Sale Price - Cost Price', max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, help_text='Commission percentage', max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, help_text='Commission earned by seller', max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('credit', 'Credit'), ('other', 'Other')], default='cash', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Payment reference/receipt number', max_length=100)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='completed', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.OneToOneField(blank=True, help_text='Associated sell agreement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_transaction', to='agreements.agreement')),
                ('phone', models.ForeignKey(help_text='Phone that was sold', on_delete=django.db.models.deletion.PROTECT, related_name='sales_transactions', to='agreements.phone')),
                ('seller', models.ForeignKey(help_text='Seller who made this sale', limit_choices_to={'role': 'seller'}, on_delete=django.db.models.deletion.CASCADE, related_name='sales_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Transaction',
                'verbose_name_plural': 'Sales Transactions',
                'ordering': ['-sale_date'],
                'indexes': [models.Index(fields=['transaction_id'], name='sales_sales_transac_913d67_idx'), models.Index(fields=['seller', '-sale_date'], name='sales_sales_seller__37baaa_idx'), models.Index(fields=['status', '-sale_date'], name='sales_sales_status_bb6b48_idx')],
            },
        ),
        migrations.CreateModel(
            name='SellerPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_sales', models.IntegerField(default=0, help_text='Total number of sales')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Total sales revenue', max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_profit_margin', models.DecimalField(decimal_places=2, default=0, help_text='Average profit margin %', max_digits=5)),
                ('rank_in_period', models.IntegerField(blank=True, help_text='Seller rank compared to others', null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(limit_choices_to={'role': 'seller'}, on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller Performance',
                'verbose_name_plural': 'Seller Performance Records',
                'ordering': ['-period_start', '-total_revenue'],
                'indexes': [models.Index(fields=['seller', 'period_type', '-period_start'], name='sales_selle_seller__d7f4f4_idx')],
                'unique_together': {('seller', 'period_type', 'period_start')},
            },
        ),
    ]
