# Generated by Django 5.2.4 on 2025-12-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Format: 07XXXXXXXX', max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('seller', 'Seller'), ('manager', 'Manager')], help_text='Role for regular users. Superusers do not need a role.', max_length=10, null=True),
        ),
    ]
