# Generated by Django 5.2.4 on 2025-12-17 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(db_index=True, help_text='15-digit IMEI number', max_length=15, unique=True)),
                ('serial_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('other', 'Other')], default='used', max_length=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('assigned', 'Assigned')], default='available', max_length=10)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_owner', models.ForeignKey(help_text='Current owner/seller of this phone', on_delete=django.db.models.deletion.CASCADE, related_name='owned_phones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_type', models.CharField(choices=[('buy', 'Buy Agreement'), ('sell', 'Sell Agreement')], max_length=4)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_national_id', models.CharField(max_length=30)),
                ('customer_phone', models.CharField(help_text='Format: 07XXXXXXXX', max_length=15)),
                ('customer_address', models.TextField()),
                ('id_photo', models.ImageField(blank=True, null=True, upload_to='agreements/id_photos/')),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='agreements/passport_photos/')),
                ('signature', models.TextField(blank=True, help_text='Base64 canvas signature data')),
                ('signature_photo', models.ImageField(blank=True, help_text='Signature image file for PDF', null=True, upload_to='agreements/signatures/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(help_text='Seller/dealer creating this agreement', on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to=settings.AUTH_USER_MODEL)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='agreements.phone')),
            ],
            options={
                'verbose_name': 'Agreement',
                'verbose_name_plural': 'Agreements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhoneAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True, help_text='Optional message for the recipient')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_seller', models.ForeignKey(help_text='Seller assigning the phone', on_delete=django.db.models.deletion.CASCADE, related_name='assignments_sent', to=settings.AUTH_USER_MODEL)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='agreements.phone')),
                ('to_seller', models.ForeignKey(help_text='Seller receiving the phone', on_delete=django.db.models.deletion.CASCADE, related_name='assignments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phone Assignment',
                'verbose_name_plural': 'Phone Assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhoneHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('assign', 'Assign'), ('approve', 'Approve Assignment'), ('reject', 'Reject Assignment')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='agreements.agreement')),
                ('from_user', models.ForeignKey(blank=True, help_text='User initiating the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_from', to=settings.AUTH_USER_MODEL)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='agreements.phone')),
                ('to_user', models.ForeignKey(blank=True, help_text='User receiving (for assignments)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phone History',
                'verbose_name_plural': 'Phone Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['imei', 'serial_number'], name='agreements__imei_dae259_idx'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['status', 'current_owner'], name='agreements__status_9a2351_idx'),
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['agreement_type', 'seller'], name='agreements__agreeme_c228ae_idx'),
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['-created_at'], name='agreements__created_0e3665_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneassignment',
            index=models.Index(fields=['status', 'to_seller'], name='agreements__status_959d7d_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneassignment',
            index=models.Index(fields=['-created_at'], name='agreements__created_fa054a_idx'),
        ),
        migrations.AddIndex(
            model_name='phonehistory',
            index=models.Index(fields=['phone', '-created_at'], name='agreements__phone_i_0dc30a_idx'),
        ),
    ]
